name: semitnet-paper
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.10.9
  - pytorch=1.13.1
  - torchvision=0.14.1
  - pytorch-cuda=11.7
  - pip
  - pip:
      - huggingface_hub>=0.24
      - opencv-python
      - cityscapesscripts
      - pytorch_pretrained_vit
      - pycocotools
      - matplotlib
      - pyyaml
